services:
  luan-portfolio:
    container_name: "luan-portfolio"
    restart: unless-stopped
    volumes:
      - ./nginx/log:/var/log/nginx

networks:
  default:
    name: nginx-proxy-manager
    external: true
