name: Deploy na hostinger

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configura SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Executa comandos de deploy
        env:
          SSH_HOST: ${{ secrets.VPS_HOST }}
          SSH_USER: ${{ secrets.VPS_SSH_USER }}
          PROJECT_DIR: ${{ secrets.PROJECT_DIR }}
        run: |
          ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "
            cd ${PROJECT_DIR}
            git pull origin main
            docker compose down
            docker compose up -d --build
          "
